version: '3.8' # Or your preferred Docker Compose version

services:
  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.26.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - > # Multi-line command
        /nakama/nakama migrate up --database.address "${NAKAMA_DB_DSN}" &&
        exec /nakama/nakama --name nakama1 --database.address "${NAKAMA_DB_DSN}" --logger.level DEBUG --session.token_expiry_sec 7200
        # Note: --metrics.prometheus_port flag is removed as Prometheus is not used.
    restart: "no" # As per your previous configurations
    volumes:
      - ./:/nakama/data # For custom modules (Lua, Go, TS), if you use them.
    expose: # Internal ports Nakama listens on (Prometheus port 9100 removed)
      - "7349" # Optional, often for a separate Admin API port if configured
      - "7350" # Default gRPC + HTTP API port
      - "7351" # Default WebSocket port
    ports: # Ports exposed to your host machine
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # MySQL Data Source Name (DSN)
      # Format: username:password@tcp(host:port)/database_name?param1=value1&param2=value2
      NAKAMA_DB_DSN: "root:EDclbxzNsGLTILbbPzHXemNHdwcmnbBK@tcp(caboose.proxy.rlwy.net:44671)/nakama?parseTime=true&tls=skip-verify"
      # --- IMPORTANT ---
      # 1. Replace 'nakama' if your database name is different.
      # 2. Adjust 'tls' parameter if needed:
      #    - `tls=skip-verify`: Encrypts, doesn't verify server cert (common for managed DBs).
      #    - `tls=true`: Encrypts, verifies server cert against system CAs.
      #    - `tls=false` or remove `&tls=...`: If SSL is not required/used (uncommon for remote DBs).
      # 3. Ensure `parseTime=true` is kept, it's important for Go's handling of MySQL date/time types.

# No other services (like a local mysql or prometheus) are defined.
# No external volumes are defined as the database is external.
